### ISSUE TITLE
Error: Cannot find module 'hyperapp-render/browser'

### ISSUE THREAD

**Issue by whaaaley** [kriasoft/hyperapp-render#21]
In a recent update it looks like the import name was broken or changed. What's the alternative to this import now? Is this still the correct way?

```
import { renderToString } from 'hyperapp-render/browser'
```

I didn't see anything in release notes but I did see quite a few updates in `package.json` so I'm unsure.

**Comment by frenzzy** [comment]
Hi! Just use `import { renderToString } from 'hyperapp-render'`, it will automatically import node version for node.js and browser version for all other environments.

`import { renderToString } from 'hyperapp-render/browser'` wasn't documented.

**Comment by whaaaley** [comment]
Gotcha! It seems to work fine however rollup is warning me about an unresolved dependency.

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
stream (imported by node_modules/hyperapp-render/esm/node.js)
```

I'm using rollup then running the output in node. I think this is why I opted to use `'hyperapp-render/browser'` directly.

**Comment by frenzzy** [comment]
With rollup you have to use [`browser: true`](https://github.com/rollup/plugins/tree/master/packages/node-resolve#browser) option for `@rollup/plugin-node-resolve` plugin:
```js
const nodeResolve = require('@rollup/plugin-node-resolve')
// ...
plugins: [nodeResolve({ browser: true })]
```

**Comment by whaaaley** [comment]
I've added the `browser: true` option but it doesn't seem to have any effect.

**Comment by frenzzy** [comment]
It should work. Maybe you have multiple rollup configurations and didn't apply plugin for all. Hard to help without seeing the code :)

Alternatively you can change import again, but it may change in minor versions in the future:
```js
import { renderToString } from 'hyperapp-render/esm/browser.js'
// or
const { renderToString } = require('hyperapp-render/commonjs/browser.js')
```

**Comment by whaaaley** [comment]
Perfect. This one seemed to work without a warning. 👍 
```
import { renderToString } from 'hyperapp-render/esm/browser'
```

Fwiw, this is the command I'm running, so I'm positive the config is getting added. Maybe it's something with the `--format` flag?
```
rollup src/index.js --config --format cjs | node > public/index.html
```

**Comment by frenzzy** [comment]
Looks like you are overriding [`mainFields`](https://github.com/rollup/plugins/tree/master/packages/node-resolve#mainfields):
```js
resolve({
  mainFields: ['module'] // 1
})
```
should be
```js
resolve({ mainFields: ['browser', 'module'] })
// or
resolve({ browser: true })
```

**Comment by whaaaley** [comment]
Gotcha. That makes sense! I wasn't really thinking what the use case of `mainFields` was actually for. I only used it to get around the symlink issue.
